language: rust
cache: cargo
os:
- linux
- osx
- windows
before_install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get -y install musl-tools
  fi
before_script: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    rustup target add x86_64-unknown-linux-musl
  fi
script: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    cargo build --target x86_64-unknown-linux-musl --verbose --release
    cargo test --target x86_64-unknown-linux-musl --verbose
  else
    cargo build --verbose --release
    cargo test --verbose
  fi
after_success: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    mv target/x86_64-unknown-linux-musl/release/cds "target/release/cds-${TRAVIS_TAG:-unstable}-$TRAVIS_OS_NAME"
  else
    mv target/release/cds "target/release/cds-${TRAVIS_TAG:-unstable}-$TRAVIS_OS_NAME"
  fi
deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      branch: master
    file_glob: true
    file:
      - target/release/cds-*
    api_key: $GITHUB_API_KEY
