language: rust
cache: cargo
os:
- linux
- osx
- windows
script: cargo build --verbose --release; cargo test --verbose
after_success:
  - mv target/release/cds "target/release/cds-${TRAVIS_TAG:-unstable}-$TRAVIS_OS_NAME"
deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      branch: master
    file_glob: true
    file:
      - target/release/cds-*
    api_key: $GITHUB_API_KEY
